spring:
   datasource:
      username: user_project
      password: password
      url: jdbc:mysql://localhost:3306/user_project
   
   jpa:
      hibernate:
         ddl-auto: create
      show-sql: true
      
   sql:
      init:
         mode: never
   